
name: mirror

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  build:
    name: mirror
    runs-on: ubuntu-latest
    steps:
      - uses: cc332030/git-mirror-action@main
        timeout-minutes: 2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          destination: gitee
