
name: mirror

on:
  workflow_call:
    inputs:
      destination:
        required: false
        type: string
        default: 'gitee'
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  build:
    name: mirror
    runs-on: ubuntu-latest
    steps:
      - uses: cc332030/git-mirror-action@main
        timeout-minutes: 2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          destination: ${{ inputs.destination }}
