
name: mirror

on: push

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - run: ${{ secrets.INIT_SSH }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: ${{ secrets.MIRROR_GITHUB }}
