
name: mirror

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      DESTINATION:
        required: false

jobs:
  mirror:
    name: mirror
    runs-on: ubuntu-latest
    steps:
      - name: init-ssh-pre
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh-pre.sh | sudo sh
      - name: init-ssh
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh.sh | sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: mirror
        run: curl -sL https://github.com/cc332030/git/raw/master/script/mirror/linux/mirror-github.sh | sh
        env:
          DESTINATION: ${{ secrets.DESTINATION }}
      - name: init-ssh-clean
        run: curl -sL https://github.com/cc332030/linux/raw/master/script/init-ssh/init-ssh-clean.sh | sh
